local_costmap:
   global_frame: odom
   robot_base_frame: base_link
   update_frequency: 10.0
   publish_frequency: 2.0
   static_map: false
   rolling_window: true
   width: 4
   height: 4
   resolution: 0.02
   transform_tolerance: 1.0
